#!name=Apple WLOC 定位修改
#!desc=修改 Apple 网络定位返回坐标 | 选点页面: https://wloc.legclub.cyou/ | 脚本来源: berths7midland/wloc-time-capsule
#!author=berths7midland (time-capsule)
#!homepage=https://github.com/berths7midland/wloc-time-capsule

[rewrite_local]
^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc url script-response-body https://raw.githubusercontent.com/berths7midland/wloc-time-capsule/main/dist/wloc.js
^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save url script-echo-response https://raw.githubusercontent.com/berths7midland/wloc-time-capsule/main/dist/wloc-settings.js

[mitm]
hostname = gs-loc.apple.com, gs-loc-cn.apple.com
